<div style="border-bottom: 4px solid #003366; margin-bottom: 20px; padding-bottom: 10px; display: flex; justify-content: space-between; align-items: center;">
    <div style="flex-grow: 1;">
        <h1 style="color: #003366; font-family: 'Helvetica', sans-serif; margin-bottom: 5px;">MAT2605: Cálculo Científico I</h1>
        <h2 style="color: #555; margin-top: 0; margin-bottom: 10px;">Laboratorio 03: Normas y n&uacutemero de condici&oacuten, M&eacute;todos iterativos</h2>
        <p style="margin: 2px 0;"><b>Profesores:</b> Thomas F&uuml;hrer y Manuel A. Sánchez | <b>Fecha:</b> 27 de Marzo, 2026</p>
        <p style="margin: 2px 0;"><b>Institución:</b> Facultad de Matemáticas, Pontificia Universidad Católica de Chile</p>
    </div>
    <div style="flex: 0 0 auto; margin-left: 20px;">
        <img src="../source/FacMatematicas-15.png" 
             alt="Logo UC" 
             style="height: 60px; width: auto;">
    </div>

</div>

<div style="border: 1px solid #2980b9; border-left: 8px solid #2980b9; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
    <h3 style="color: #2980b9; margin-top: 0;">🎯 Objetivos de la Sesión</h3>
    <ul>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>

<div style="background-color: #e8f5e9; border-left: 5px solid #4caf50; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
    <h3 style="color: #2e7d32; margin-top: 0;">👤 Identificación del Estudiante</h3>
    <p style="margin-bottom: 10px; color: #555;">Por favor, completa tus datos antes de comenzar:</p>
    <ul style="list-style-type: none; padding-left: 0; color: #333;">
        <li style="margin-bottom: 5px;"><b>📌 Nombre Completo:</b> _______________________________________</li>
        <li style="margin-bottom: 5px;"><b>📌 Rol / Nº Alumno:</b> _________________________</li>
    </ul>
    <p style="font-size: 0.85em; color: #2e7d32; margin-top: 15px; border-top: 1px solid #a5d6a7; padding-top: 5px;">
        <i>💡 Haz doble clic en esta celda para editarla con tus datos.</i>
    </p>
</div>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys

# INTENTO DE CONFIGURACIÓN DE ESTILO (Compatible con versiones viejas y nuevas)
try:
    plt.style.use('seaborn-v0_8-whitegrid') # Nombre nuevo (Matplotlib 3.6+)
except OSError:
    plt.style.use('seaborn-whitegrid')      # Nombre antiguo

plt.rcParams['figure.figsize'] = (10, 6)

print(f"Versión de Numpy: {np.__version__}")
print(f"Estilo usado: {plt.style.context}")

Versión de Numpy: 1.23.5
Estilo usado: <function context at 0x0000029C2608E710>


<div class="alert-block alert-warning "; style=" border-left: 5px solid #ffc107; padding: 15px; border-radius: 5px;">
    <h2 > </h2>
    <h3 style="color: #d35400; margin-top: 0;">📚 Teoría:</h3>
    <p>Normas </p>
    <p>Numero de condcion</p>   
    <p>Metodo iterativo basico</p>
</div>

## Jacobi

In [21]:
import numpy as np

def metodo_de_Jacobi(A, b, x0, max_iter=100, tol=1e-8):
    """
    Resuelve el sistema Ax = b usando el método de Jacobi.
    Input: A, b, x0 (vector inicial)
    Output: x (solución aproximada), residuals (historial de errores)
    """
    x = x0.copy()
    n = len(b)
    residuals = []
    
    for k in range(max_iter):
        # Calcular el residuo actual
        residual = b - np.dot(A, x)
        norm_residual = np.linalg.norm(residual)
        residuals.append(norm_residual)
        
        # Criterio de parada
        if norm_residual < tol:
            print(f"J: Convergencia alcanzada en la iteración {k+1} | Error: {norm_residual:.6e}")
            return x, residuals
        x_old = x.copy()
        # Calcular los nuevos valores de x
        for i in range(n):
            suma = np.dot(A[i, :i], x_old[:i]) + np.dot(A[i, i+1:], x_old[i+1:])
            # Jacobi
            x[i] = (b[i] - suma) / A[i, i]
            
    print(f"J: Número máximo de iteraciones alcanzado. Error final: {norm_residual:.6e}")
    return x, residuals

def metodo_de_GaussSeidel(A, b, x0, max_iter=100, tol=1e-8):
    """
    Resuelve el sistema Ax = b usando el método de Gauss-Seidel.
    Input: A, b, x0 (vector inicial)
    Output: x (solución aproximada), residuals (historial de errores)
    """
    x = x0.copy()
    n = len(b)
    residuals = []
    
    for k in range(max_iter):
        # Calcular el residuo actual
        residual = b - np.dot(A, x)
        norm_residual = np.linalg.norm(residual)
        residuals.append(norm_residual)
        
        # Criterio de parada
        if norm_residual < tol:
            print(f"GS: Convergencia alcanzada en la iteración {k+1} | Error: {norm_residual:.6e}")
            return x, residuals
        for i in range(n):
            suma = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i+1:], x[i+1:])
            # Gauss-Seidel
            x[i] = (b[i] - suma) / A[i, i]
            
    print(f"GS: Número máximo de iteraciones alcanzado. Error final: {norm_residual:.6e}")
    return x, residuals

def metodo_de_SOR(A, b, x0, w=1.0, max_iter=100, tol=1e-8):
    """
    Resuelve el sistema Ax = b usando el método de SOR.
    Input: A, b, x0 (vector inicial)
    Output: x (solución aproximada), residuals (historial de errores)
    """
    x = x0.copy()
    n = len(b)
    residuals = []
    
    for k in range(max_iter):
        # Calcular el residuo actual
        residual = b - np.dot(A, x)
        norm_residual = np.linalg.norm(residual)
        residuals.append(norm_residual)
        # Criterio de parada
        if norm_residual < tol:
            print(f"SOR: Convergencia alcanzada en la iteración {k+1} | Error: {norm_residual:.6e}")
            return x, residuals
        for i in range(n):
            suma = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i+1:], x[i+1:])
            # SOR
            x[i] = (1.0 - w) * x[i] + (w / A[i, i]) * (b[i] - suma)
            
    print(f"SOR: Número máximo de iteraciones alcanzado. Error final: {norm_residual:.6e}")
    return x, residuals

In [24]:
A1 = np.array([[7,-4],[-8,9]])
b1 = np.array([3,-4])
x0 = np.array([-1.0,3.0])
x = metodo_de_Jacobi(A1,b1,x0)
x = metodo_de_GaussSeidel(A1,b1,x0)
x = metodo_de_SOR(A1,b1,x0, w=1.02)

J: Convergencia alcanzada en la iteración 67 | Error: 8.765331e-09
GS: Convergencia alcanzada en la iteración 32 | Error: 9.199708e-09
SOR: Convergencia alcanzada en la iteración 31 | Error: 5.884392e-09


In [25]:
A2 = np.array([[1.0, 0.5,0.5],[0.5,1.0,0.5],[0.5,0.5,1.0]])
b2 = np.array([1.0,-.1,0.0])
x = metodo_de_Jacobi(A2,b2,np.ones(3))
x = metodo_de_GaussSeidel(A2,b2,np.ones(3))

J: Número máximo de iteraciones alcanzado. Error final: 2.944486e+00
GS: Convergencia alcanzada en la iteración 20 | Error: 7.302829e-09


## analisis con las matrices de iteracion de los metodos

In [29]:
D = np.diag(np.diag(A2))
L = np.tril(A2, k=-1)
U = np.triu(A2, k=1)
print(" D:\n", D,"\n L:\n", L,"\n U:\n", U)

# Matriz e iteracion de Jacobi
T_J = -np.linalg.inv(D)@ (L+U)
print("T_J:\n",T_J)

# condicion de radio espectral
rho_J = max(abs(np.linalg.eigvals(T_J)))
print(" rho_J = ", rho_J, "==> no converge!")

# Matriz e iteracion de Gauss-Seidel
T_G = -np.linalg.inv(D+L)@ (U)
print("T_G:\n",T_G)

# condicion de radio espectral
rho_G = max(abs(np.linalg.eigvals(T_G)))
print(" rho_GS = ", rho_G, "==> converge!")

 D:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 L:
 [[0.  0.  0. ]
 [0.5 0.  0. ]
 [0.5 0.5 0. ]] 
 U:
 [[0.  0.5 0.5]
 [0.  0.  0.5]
 [0.  0.  0. ]]
T_J:
 [[ 0.  -0.5 -0.5]
 [-0.5  0.  -0.5]
 [-0.5 -0.5  0. ]]
 rho_J =  0.9999999999999998 ==> no converge!
T_G:
 [[ 0.    -0.5   -0.5  ]
 [ 0.     0.25  -0.25 ]
 [ 0.     0.125  0.375]]
 rho_GS =  0.3535533905932738 ==> converge!


In [30]:
A3 = np.array([[1,2,-2],[1,1,1],[2,2,1]],dtype = np.float64)
D = np.diag(np.diag(A3))
L = np.tril(A3, k=-1)
U = np.triu(A3, k=1)

# Matriz e iteracion de Jacobi
T_J = -np.linalg.inv(D)@ (L+U)

print("T_J:\n",T_J)
# condicion de radio espectral
rho_J = max(abs(np.linalg.eigvals(T_J)))
print(" rho_J = ", rho_J, "==> converge!")

# Matriz e iteracion de Gauss-Seidel
T_G = -np.linalg.inv(D+L)@ (U)
print("T_G:\n",T_G)
# condicion de radio espectral
rho_G = max(abs(np.linalg.eigvals(T_G)))
print(" rho_G = ", rho_G, "==> no converge!")

T_J:
 [[ 0. -2.  2.]
 [-1.  0. -1.]
 [-2. -2.  0.]]
 rho_J =  1.080934114523089e-05 ==> converge!
T_G:
 [[ 0. -2.  2.]
 [ 0.  2. -3.]
 [ 0.  0.  2.]]
 rho_G =  2.0 ==> no converge!


## Problemas de ayudantia 3

- Usando la norma usual ($\|\cdot \|_2$), calcule analíticamente (a mano) el número de condición $\kappa(A)$ y $\kappa(B)$ de las matrices:

$$A = \begin{bmatrix} 0 & 4 & -3 \\ -2 & 0 & 0 \\ 0 & 3 & 4 \end{bmatrix} \quad B = \begin{bmatrix} -2 & 0 & -5 \\ 0 & -2 & 5 \\ -5 & 5 & -7 \end{bmatrix}$$

Y revise sus repuestas con ```numpy```.

- El método de Richardson es un método iterativo para la solución de sistemas lineales. Para el sistema lineal $Ax = b$, la matriz $A$ se divide de la forma $A = M - N$, con $M = \frac{1}{\omega}I$ y $\omega \in \mathbb{R}$ un parametro.

1. Justifique que $M$ es fácil de invertir.
2. Identifique la matriz de recurrencia $T$ y el vector $c$ tal que $x^{(k+1)} = Tx^{(k)} + c$.
3. Ahora suponga que $A^T = A \succ 0$ (es decir, es simétrica definida positiva), encuentre una condición que debe cumplir $\omega$, en función de los valores propios de $A$, para que el método converga. ¿Siempre es posible escoger un $\omega$ que garantize que converga?