<div style="border-bottom: 4px solid #003366; margin-bottom: 20px; padding-bottom: 10px; display: flex; justify-content: space-between; align-items: center;">
    <div style="flex-grow: 1;">
        <h1 style="color: #003366; font-family: 'Helvetica', sans-serif; margin-bottom: 5px;">MAT2605: Cálculo Científico I</h1>
        <h2 style="color: #555; margin-top: 0; margin-bottom: 10px;">Laboratorio 03: Normas y n&uacutemero de condici&oacuten, M&eacute;todos iterativos</h2>
        <p style="margin: 2px 0;"><b>Profesores:</b> Thomas F&uuml;hrer y Manuel A. Sánchez | <b>Fecha:</b> 27 de Marzo, 2026</p>
        <p style="margin: 2px 0;"><b>Institución:</b> Facultad de Matemáticas, Pontificia Universidad Católica de Chile</p>
    </div>
    <div style="flex: 0 0 auto; margin-left: 20px;">
        <img src="../source/FacMatematicas-15.png" 
             alt="Logo UC" 
             style="height: 60px; width: auto;">
    </div>

</div>

<div style="border: 1px solid #2980b9; border-left: 8px solid #2980b9; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
    <h3 style="color: #2980b9; margin-top: 0;">🎯 Objetivos de la Sesión</h3>
    <ul>
        <li>Familiarse con el c&aacute;lculo de normas vectoriales/matriciales</li>
        <li>Condicionamiento de sistemas lineales</li>
        <li>Estudiar convergencia de m&eacute;todos iterativos</li>
    </ul>
</div>

<div style="background-color: #e8f5e9; border-left: 5px solid #4caf50; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
    <h3 style="color: #2e7d32; margin-top: 0;">👤 Identificación del Estudiante</h3>
    <p style="margin-bottom: 10px; color: #555;">Por favor, completa tus datos antes de comenzar:</p>
    <ul style="list-style-type: none; padding-left: 0; color: #333;">
        <li style="margin-bottom: 5px;"><b>📌 Nombre Completo:</b> _______________________________________</li>
        <li style="margin-bottom: 5px;"><b>📌 Rol / Nº Alumno:</b> _________________________</li>
    </ul>
    <p style="font-size: 0.85em; color: #2e7d32; margin-top: 15px; border-top: 1px solid #a5d6a7; padding-top: 5px;">
        <i>💡 Haz doble clic en esta celda para editarla con tus datos.</i>
    </p>
</div>

In [53]:
import numpy as np
import matplotlib.pyplot as plt
import sys

# INTENTO DE CONFIGURACIÓN DE ESTILO (Compatible con versiones viejas y nuevas)
try:
    plt.style.use('seaborn-v0_8-whitegrid') # Nombre nuevo (Matplotlib 3.6+)
except OSError:
    plt.style.use('seaborn-whitegrid')      # Nombre antiguo

plt.rcParams['figure.figsize'] = (10, 6)

print(f"Versión de Numpy: {np.__version__}")
print(f"Estilo usado: {plt.style.context}")

Versión de Numpy: 2.4.3
Estilo usado: <function context at 0x7efc9f4f7480>


<div class="alert-block alert-warning "; style=" border-left: 5px solid #ffc107; padding: 15px; border-radius: 5px;">
    <h2 > </h2>
    <h3 style="color: #d35400; margin-top: 0;">📚 Teoría:</h3>
    <p>Norma vectorial (norma p): $\|x\|_p = \left( \sum_{j=1}^N |x_j|^p \right)^{1/p}, \quad p\in[1,\infty), \quad x\in\mathbb{R}^N, \qquad \text{norma infinito }\|x\|_\infty = \max_{1\leq i\leq N} |x_i|$
    </p>
    Norma matricial inducida: $\|A\| = \max_{x\in\mathbb{R}^N,\,\|x\|=1} \frac{\|Ax\|}{\|x\|}, \quad A\in \mathbb{R}^{N\times N}$
    <p>Norma Frobenius $\|A\|_F = \sqrt{\sum_{i,j=1}^N |a_{ij}|^2}$
    <p>N&uacute;mero de condici&oacute;n</p>
    $$\mathrm{cond}(A) = \|A\|\,\|A^{-1}\|$$
    <p>M&eacute;todo iterativo b&aacute;sico</p>
    $$ x^{(k+1)} = T x^{(k)} + b, \quad x^{(0)} \text{ vector inicial dado}$$
    donde $T$ es la matriz de iteraci&oacute;n. (Para asegurar convergencia es suficiente que $\rho(T)<1$ donde $\rho$ es el radio espectral. Se analiza en detalles durante las clases de la semana que viene).
</div>

# Normas

En Python (NumPy) es posible calcular normas mediante <code>np.linalg.norm(x)</code> que calcula la norma euclidiana del vector $x$.

Para calcular las normas $\|\cdot\|_p$ se puede usar un segundo argumento: <code>np.linalg.norm(x,p)</code>.
Para la norma infinito se usa el "s&iacute;mbolo" $\infty$ que se representa en Python (NumPy) como <code>np.inf</code>.

En Python es posible calcular la norma $p$ para $p=1,2,\infty$ de una matriz, pero no es posible con otros valores de $p$.
Es posible calcular la norma Frobenius con <code>np.linalg.norm(A)</code> o <code>np.linalg.norm(A,'fro')</code>

*Cuidado*: Para calcular la norma inducida por la norma $2$ hay que usar <code>np.linalg.norm(A,2)</code>

In [4]:
# Normas vectoriales
x = np.array([1,1,1,1])
print("Vector x: ",x)

print("Norma euclidiana = ", np.linalg.norm(x))
print("Norma 1 = ", np.linalg.norm(x,1))
print("Norma inf = ",np.linalg.norm(x,np.inf))

print("Norma Pi = ",np.linalg.norm(x,np.pi))

# Normas matriciales
A = np.array([[1,-1,-1,-1],[0,1,-1,-2],[0,0,1,0],[0,0,0,3]])
print("Matriz A:\n",A)

print("Norma 2 = ", np.linalg.norm(A,2))
print("Norma 1 = ", np.linalg.norm(A,1))
print("Norma inf = ",np.linalg.norm(A,np.inf))
print("Norma Frobenius = ",np.linalg.norm(A,'fro'))
print("Norma (sin dar segundo argumento) = ",np.linalg.norm(A))

print("Norma Pi = ",np.linalg.norm(A,np.pi))

Vector x:  [1 1 1 1]
Norma euclidiana =  2.0
Norma 1 =  4.0
Norma inf =  1.0
Norma Pi =  1.5546822754821001
Matriz A:
 [[ 1 -1 -1 -1]
 [ 0  1 -1 -2]
 [ 0  0  1  0]
 [ 0  0  0  3]]
Norma 2 =  3.8641592082012663
Norma 1 =  6.0
Norma inf =  4.0
Norma Frobenius =  4.47213595499958
Norma (sin dar segundo argumento) =  4.47213595499958


ValueError: Invalid norm order for matrices.

# N&uacute;mero de condici&oacute;n

En Python (NumPy) podemos usar <code>np.linalg.cond(A,arg)</code> para calcular el n&uacute;mero de condici&oacute;n de una matriz $A$. (<code>arg</code> se elige como antes para las normas)

*Cuidado:* <code>np.linalg.cond(A)</code> calcula <code>np.linalg.cond(A,2)</code>

In [5]:
print('Numero condicion (norma Frobenius) = ',np.linalg.cond(A,'fro'))
print('Numero condicion (norma 2) = ',np.linalg.cond(A,2))
print('Numero condicion (norma 1) = ',np.linalg.cond(A,1))
print('Numero condicion (norma 1) = ',np.linalg.cond(A,np.inf))

Numero condicion (norma Frobenius) =  14.52966314513558
Numero condicion (norma 2) =  11.993601585424015
Numero condicion (norma 1) =  24.0
Numero condicion (norma 1) =  20.0


Tenemos la cota
$$\frac{\|\Delta x\|}{\|x\|}\leq \mathrm{cond}(A) \frac{\|\Delta b\|}{\|b\|}$$

En el c&oacute;digo abajo se usa la norma $2$. Que se observa cuando se cambia a la norma $1$ y/o $\infty$?

In [44]:
delta = 0.00001
p = 2
A = np.array([[1,1+delta],[1-delta,1]])
print('Matrix A = \n',A)
condA = np.linalg.cond(A,p)

# resolver systema lineal
b = np.array([1,1])
delta_b = np.array([-1,1])/100
x = np.linalg.solve(A,b)
delta_x = np.linalg.solve(A,delta_b)

# errores
err_rel_x = np.linalg.norm(delta_x,p)/np.linalg.norm(x,p)
err_rel_b = np.linalg.norm(delta_b,p)/np.linalg.norm(b,p)
print('error rel. en solucion = ',err_rel_x)
print('error rel. en dato b   = ',err_rel_b)
print('amplificacion          = ',err_rel_x/err_rel_b)
print('numero de condicion    = ',condA)

# otro ejemplo con perturbacion aleatoria
# resolver systema lineal
print('\n\nOtro ejemplo\n')
delta_b = np.random.rand(2)/1000
x = np.linalg.solve(A,b)
delta_x = np.linalg.solve(A,delta_b)

# errores
err_rel_x = np.linalg.norm(delta_x,p)/np.linalg.norm(x,p)
err_rel_b = np.linalg.norm(delta_b,p)/np.linalg.norm(b,p)
print('error rel. en solucion = ',err_rel_x)
print('error rel. en dato b   = ',err_rel_b)
print('amplificacion          = ',err_rel_x/err_rel_b)
print('numero de condicion    = ',condA)

Matrix A = 
 [[1.      1.00001]
 [0.99999 1.     ]]
error rel. en solucion =  2000.0000000238272
error rel. en dato b   =  0.01
amplificacion          =  200000.0000023827
numero de condicion    =  40000084898.939415


Otro ejemplo

error rel. en solucion =  19.612280954735994
error rel. en dato b   =  0.0005733577786156322
amplificacion          =  34206.008335824255
numero de condicion    =  40000084898.939415


# M&eacute;todo iterativo b&aacute;sico

El m&eacute;todo de Jacobi se define como
$$x^{(k+1)} = T_J x^{(k)} + c, \quad k=0,1,2,...$$
donde $T_J = D^{-1}(L+U)$, con $A = -L + D -U$ y $c = D^{-1}b$.

Es importante en una implementaci&oacute;n asegurarse que termine en pasos finitos. 
En el c&oacute;digo abajo se acota el numero de iteraciones con <code>max_iter</code>

Ademas, se incluye el criterio de parada: <code>norm_residual < tol</code>
que se traduce a: Si 
$$\|Ax^{(k)}-b\|_2< \mathrm{tol}$$
entonces termina. 
Aqui, $\|Ax^{(k)}-b\|_2$ es la norma del residuo en el $k$-esimo paso. 

Muchas veces se usa el criterio
$$\|Ax^{(k)}-b\|_2< \mathrm{tol} \times \|Ax^{(0)}-b\|_2$$
donde $\|Ax^{(0)}-b\|_2$ es la norma del residuo inicial. 
Modifique el c&oacute;digo abajo para incluir este criterio.

## Jacobi

In [48]:
def metodo_de_Jacobi(A, b, x0, max_iter=100, tol=1e-8):
    """
    Resuelve el sistema Ax = b usando el método de Jacobi.
    Input: A, b, x0 (vector inicial)
    Output: x (solución aproximada), residuals (historial de errores)
    """
    x = x0.copy()
    n = len(b)
    residuals = []
    
    for k in range(max_iter):
        # Calcular el residuo actual
        residual = b - np.dot(A, x)
        norm_residual = np.linalg.norm(residual)
        residuals.append(norm_residual)
        
        # Criterio de parada
        if norm_residual < tol:
            print(f"J: Convergencia alcanzada en la iteración {k+1} | Error: {norm_residual:.6e}")
            return x, residuals
        x_old = x.copy()
        # Calcular los nuevos valores de x
        for i in range(n):
            suma = np.dot(A[i, :i], x_old[:i]) + np.dot(A[i, i+1:], x_old[i+1:])
            # Jacobi
            x[i] = (b[i] - suma) / A[i, i]
            
    print(f"J: Número máximo de iteraciones alcanzado. Error final: {norm_residual:.6e}")
    return x, residuals

In [49]:
A1 = np.array([[7,-4],[-8,9]])
b1 = np.array([3,-4])
x0 = np.array([-1.0,3.0])
x = metodo_de_Jacobi(A1,b1,x0)

J: Convergencia alcanzada en la iteración 67 | Error: 8.765331e-09


In [50]:
A2 = np.array([[1.0, 0.5,0.5],[0.5,1.0,0.5],[0.5,0.5,1.0]])
b2 = np.array([1.0,-.1,0.0])
x = metodo_de_Jacobi(A2,b2,np.ones(3))

J: Número máximo de iteraciones alcanzado. Error final: 2.944486e+00


## An&aacute;lisis con las matrices de iteraci&oacute;n

In [51]:
D = np.diag(np.diag(A2))
L = -np.tril(A2, k=-1)
U = -np.triu(A2, k=1)
print(" D:\n", D,"\n L:\n", L,"\n U:\n", U)

# Matriz e iteracion de Jacobi
T_J = np.linalg.inv(D)@ (L+U)
print("T_J:\n",T_J)

# condicion de radio espectral
rho_J = max(abs(np.linalg.eigvals(T_J)))
print(" rho_J = ", rho_J, "==> no converge!")

 D:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 L:
 [[-0.  -0.  -0. ]
 [-0.5 -0.  -0. ]
 [-0.5 -0.5 -0. ]] 
 U:
 [[-0.  -0.5 -0.5]
 [-0.  -0.  -0.5]
 [-0.  -0.  -0. ]]
T_J:
 [[ 0.  -0.5 -0.5]
 [-0.5  0.  -0.5]
 [-0.5 -0.5  0. ]]
 rho_J =  0.9999999999999998 ==> no converge!


In [52]:
A3 = np.array([[1,2,-2],[1,1,1],[2,2,1]],dtype = np.float64)
D = np.diag(np.diag(A3))
L = np.tril(A3, k=-1)
U = np.triu(A3, k=1)

# Matriz e iteracion de Jacobi
T_J = -np.linalg.inv(D)@ (L+U)

print("T_J:\n",T_J)
# condicion de radio espectral
rho_J = max(abs(np.linalg.eigvals(T_J)))
print(" rho_J = ", rho_J, "==> converge!")

T_J:
 [[ 0. -2.  2.]
 [-1.  0. -1.]
 [-2. -2.  0.]]
 rho_J =  1.0812771377650137e-05 ==> converge!


---
<div class="alert alert-block alert-success"> 

## Ticket de Salida:

</div>

<div style="background-color: #e8f5e9; border-left: 5px solid #4caf50; padding: 15px; border-radius: 5px;">
    <h3 style="color: #2e7d32; margin-top: 0;">💻 Ejercicio 1: Definir Norma Alternativa</h3>
    <p>Considere la siguiente definici&oacute;n: $\|A\|= \mathrm{tr}(\sqrt{A^\top A})$. 
    Aqui, $B = \sqrt{A^\top A}$ es una matriz tal que $BB = A^\top A$. Puede usar la funci&oacute;n <code>scipy.linalg.sqrtm(A.T@A)</code> para calcular la matriz $B$. Ademas, se define $\mathrm{tr}(A) = \sum_{j=1}^N a_{jj}$, y se llama la traza de la matriz $A$.
        Se puede verificar que $\|\cdot\|$ es una norma y se llama la <strong>norma nuclear</strong>. 
    </p>
    <p><b>Tu tarea:</b></p>
    <ol>
        <li>Escribe un c&oacute;digo para calcular la norma nuclear.</li>
        <li>Compare la norma nuclear con las normas $\|\cdot\|_p$ ($p=1,2,\infty$) para unas matrices.</li>
        <li>Compare n&uacute;mero de condici&oacute;n en la norma nuclear con la norma $\|\cdot\|_2$ para matrices mal condicionadas (basta ver una matriz de los ejemplos de arriba).</li>
    </ol>
</div>

<div style="background-color: #e8f5e9; border-left: 5px solid #4caf50; padding: 15px; border-radius: 5px;">
    <h3 style="color: #6a1b9a; margin: 0; font-size: 1.1em;">
        ✏️ Solución / Desarrollo
    </h3>
    <p style="margin: 5px 0 0 0; font-size: 0.9em; color: #666;">
        <i>Utilice las celdas de código y texto debajo de esta línea para responder. Recuerde comentar su código.</i>
    </p>
</div>

<div style="background-color: #e8f5e9; border-left: 5px solid #4caf50; padding: 15px; border-radius: 5px;">
    <h3 style="color: #2e7d32; margin-top: 0;">💻 Ejercicio 2: Condicionamiento de sistema</h3>
    <p>Sea $A\in\mathbb{R}^{N\times N}$ una matriz tridiagonal donde los coeficientes en la diagonal tienen el valor $2$ y los coeficientes en la subdiagonal y superdiagonal son $-1$, por ejemplo, para $N=4$, la matriz es
        $$ \begin{pmatrix} 2 & -1 & 0 & 0 \\ -1 & 2 & -1 & 0 \\ 0 & -1 & 2 & -1 \\ 0 & 0 & -1 & 2\end{pmatrix} $$
    </p>
    <p><b>Tu tarea:</b></p>
    <ol>
        <li>Escriba un c&oacute;digo que genera la matriz $A$ dado $N$.</li>
        <li>Estudie el n&uacute;mero de condici&oacute;n $\mathrm{cond}_2(A)$ para $N=2^j$, $j=1,2,3,4,\ldots$</li>
        <li>Se puede observar un orden en un plot doble-logar&iacute;tmico?</li>
        <li>Que se observa en otras normas?</li>
    </ol>
    Nota: Esto tipo de matrices se genera al discretizar la ecuaci&oacute;n diferencial $-u'' = f$.
</div>

<div style="background-color: #e8f5e9; border-left: 5px solid #4caf50; padding: 15px; border-radius: 5px;">
    <h3 style="color: #6a1b9a; margin: 0; font-size: 1.1em;">
        ✏️ Solución / Desarrollo
    </h3>
    <p style="margin: 5px 0 0 0; font-size: 0.9em; color: #666;">
        <i>Utilice las celdas de código y texto debajo de esta línea para responder. Recuerde comentar su código.</i>
    </p>
</div>

<div style="background-color: #e8f5e9; border-left: 5px solid #4caf50; padding: 15px; border-radius: 5px;">
    <h3 style="color: #2e7d32; margin-top: 0;">💻 Ejercicio 3: M&eacute;todo iterativo</h3>
    <p>Para la clase de matrices de Ejercicio 2, considere el m&eacute;todo de Jacobi (ver arriba) para resolver el sistema $Ax = b$.</p>
    <p>Consideramos vectores $b$ con $b_1 = 1$, $b_N = 1$, $b_j = 0$ para $j=2,\ldots, N-1$. La soluci&oacute;n exacta $x$ entonces satisface $x_j = 1$ para $j=1,\ldots, N$.</p>
    <p><b>Tu tarea:</b></p>
    <ol>
        <li>Elige como vector inicial $x^{(0)}$ para el m&eacute;todo de Jacobi el vector nulo.</li>
        <li>Para $N=2,4,8,16,32,64,128,256,512$ determine la cantidad de iteraciones necesarias para asegurar que
        $$ \|Ax^{(k)}-b\|_2 < 10^{-6}$$
            Visualice los resultados (iteraciones sobre $N$). Que se observa?
        </li>
        <li>Determine $\|x-x^{(k)}\|_2$ ($k=1,2,3,\ldots$). Se espera convergencia lineal, es decir, $\|x-x^{(k)}\|_2 \leq q \|x-x^{(k-1)}\|_2$ con $0\leq q < 1$. Se puede observar? Trate de determinar $q$!</li>
    </ol>
</div>

<div style="background-color: #e8f5e9; border-left: 5px solid #4caf50; padding: 15px; border-radius: 5px;">
    <h3 style="color: #6a1b9a; margin: 0; font-size: 1.1em;">
        ✏️ Solución / Desarrollo
    </h3>
    <p style="margin: 5px 0 0 0; font-size: 0.9em; color: #666;">
        <i>Utilice las celdas de código y texto debajo de esta línea para responder. Recuerde comentar su código.</i>
    </p>
</div>